### ISSUE TITLE
Stream RTSP/TCP 

### ISSUE THREAD

**Issue by M-Razavi** [petergaal/RtspToTCP#1]
I have a CCTV Camera  which supports only ONVIF and RTSP/UDP. I want to stream video from this camera for multiple clients using RTSP/TCP. Is it possible to use your project for this purpose?

**Comment by petergaal** [comment]
Hi,
Yes, I think it's a good start. I practically did the same. This can act a receiver of the stream from the camera and can re-stream to more clients (for example for viewing by user). That way you can have only one connection to camera and not overload the camera.
This project doesn't have ONVIF support so you need to know the rtsp url of your camera or you need to program that part (you can query the RTSP url with a certain onvif call).
